package com.limited.app.bean;

import java.math.BigDecimal;

public class AssetinvSecind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_secind.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_secind.sec_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer secId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_secind.ind_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer indId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_secind.amount
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_secind.assetinv_id
     *
     * @mbggenerated Sat Mar 19 23:32:29 EDT 2011
     */
    private Integer assetinvId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_secind.id
     *
     * @return the value of assetinv_secind.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_secind.id
     *
     * @param id the value for assetinv_secind.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_secind.sec_id
     *
     * @return the value of assetinv_secind.sec_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getSecId() {
        return secId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_secind.sec_id
     *
     * @param secId the value for assetinv_secind.sec_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setSecId(Integer secId) {
        this.secId = secId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_secind.ind_id
     *
     * @return the value of assetinv_secind.ind_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getIndId() {
        return indId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_secind.ind_id
     *
     * @param indId the value for assetinv_secind.ind_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setIndId(Integer indId) {
        this.indId = indId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_secind.amount
     *
     * @return the value of assetinv_secind.amount
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_secind.amount
     *
     * @param amount the value for assetinv_secind.amount
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_secind.assetinv_id
     *
     * @return the value of assetinv_secind.assetinv_id
     *
     * @mbggenerated Sat Mar 19 23:32:29 EDT 2011
     */
    public Integer getAssetinvId() {
        return assetinvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_secind.assetinv_id
     *
     * @param assetinvId the value for assetinv_secind.assetinv_id
     *
     * @mbggenerated Sat Mar 19 23:32:29 EDT 2011
     */
    public void setAssetinvId(Integer assetinvId) {
        this.assetinvId = assetinvId;
    }
}