package com.limited.app.bean;

import java.math.BigDecimal;

public class Asset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.ticker
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private String ticker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.assetname
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private String assetname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.heldat
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer heldat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.benchmark
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private String benchmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.templateid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.beta
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private BigDecimal beta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.rsq
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private BigDecimal rsq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.stddev
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private BigDecimal stddev;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.id
     *
     * @return the value of asset.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.id
     *
     * @param id the value for asset.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.ticker
     *
     * @return the value of asset.ticker
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public String getTicker() {
        return ticker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.ticker
     *
     * @param ticker the value for asset.ticker
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setTicker(String ticker) {
        this.ticker = ticker == null ? null : ticker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.assetname
     *
     * @return the value of asset.assetname
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public String getAssetname() {
        return assetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.assetname
     *
     * @param assetname the value for asset.assetname
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setAssetname(String assetname) {
        this.assetname = assetname == null ? null : assetname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.heldat
     *
     * @return the value of asset.heldat
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getHeldat() {
        return heldat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.heldat
     *
     * @param heldat the value for asset.heldat
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setHeldat(Integer heldat) {
        this.heldat = heldat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.benchmark
     *
     * @return the value of asset.benchmark
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public String getBenchmark() {
        return benchmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.benchmark
     *
     * @param benchmark the value for asset.benchmark
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setBenchmark(String benchmark) {
        this.benchmark = benchmark == null ? null : benchmark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.templateid
     *
     * @return the value of asset.templateid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.templateid
     *
     * @param templateid the value for asset.templateid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.beta
     *
     * @return the value of asset.beta
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public BigDecimal getBeta() {
        return beta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.beta
     *
     * @param beta the value for asset.beta
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setBeta(BigDecimal beta) {
        this.beta = beta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.rsq
     *
     * @return the value of asset.rsq
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public BigDecimal getRsq() {
        return rsq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.rsq
     *
     * @param rsq the value for asset.rsq
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setRsq(BigDecimal rsq) {
        this.rsq = rsq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.stddev
     *
     * @return the value of asset.stddev
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public BigDecimal getStddev() {
        return stddev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.stddev
     *
     * @param stddev the value for asset.stddev
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setStddev(BigDecimal stddev) {
        this.stddev = stddev;
    }
}