package com.limited.app.bean;

import java.math.BigDecimal;

public class AssetinvAlloc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_alloc.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_alloc.assetinv_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer assetinvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_alloc.alloctype_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer alloctypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_alloc.amount
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private BigDecimal amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_alloc.id
     *
     * @return the value of assetinv_alloc.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_alloc.id
     *
     * @param id the value for assetinv_alloc.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_alloc.assetinv_id
     *
     * @return the value of assetinv_alloc.assetinv_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getAssetinvId() {
        return assetinvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_alloc.assetinv_id
     *
     * @param assetinvId the value for assetinv_alloc.assetinv_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setAssetinvId(Integer assetinvId) {
        this.assetinvId = assetinvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_alloc.alloctype_id
     *
     * @return the value of assetinv_alloc.alloctype_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getAlloctypeId() {
        return alloctypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_alloc.alloctype_id
     *
     * @param alloctypeId the value for assetinv_alloc.alloctype_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setAlloctypeId(Integer alloctypeId) {
        this.alloctypeId = alloctypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_alloc.amount
     *
     * @return the value of assetinv_alloc.amount
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_alloc.amount
     *
     * @param amount the value for assetinv_alloc.amount
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}