package com.limited.app.bean;

import java.math.BigDecimal;

public class AssetinvInter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_inter.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_inter.inter_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer interId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_inter.amount
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetinv_inter.assetinv_id
     *
     * @mbggenerated Sat Mar 19 23:32:29 EDT 2011
     */
    private Integer assetinvId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_inter.id
     *
     * @return the value of assetinv_inter.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_inter.id
     *
     * @param id the value for assetinv_inter.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_inter.inter_id
     *
     * @return the value of assetinv_inter.inter_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getInterId() {
        return interId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_inter.inter_id
     *
     * @param interId the value for assetinv_inter.inter_id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setInterId(Integer interId) {
        this.interId = interId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_inter.amount
     *
     * @return the value of assetinv_inter.amount
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_inter.amount
     *
     * @param amount the value for assetinv_inter.amount
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetinv_inter.assetinv_id
     *
     * @return the value of assetinv_inter.assetinv_id
     *
     * @mbggenerated Sat Mar 19 23:32:29 EDT 2011
     */
    public Integer getAssetinvId() {
        return assetinvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetinv_inter.assetinv_id
     *
     * @param assetinvId the value for assetinv_inter.assetinv_id
     *
     * @mbggenerated Sat Mar 19 23:32:29 EDT 2011
     */
    public void setAssetinvId(Integer assetinvId) {
        this.assetinvId = assetinvId;
    }
}