package com.limited.app.bean;

public class Industry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.ind_name
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private String indName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.id
     *
     * @return the value of industry.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.id
     *
     * @param id the value for industry.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.ind_name
     *
     * @return the value of industry.ind_name
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public String getIndName() {
        return indName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.ind_name
     *
     * @param indName the value for industry.ind_name
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setIndName(String indName) {
        this.indName = indName == null ? null : indName.trim();
    }
}