package com.limited.app.bean;

public class Institution {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.inst_name
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private String instName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institution.id
     *
     * @return the value of institution.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institution.id
     *
     * @param id the value for institution.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institution.inst_name
     *
     * @return the value of institution.inst_name
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public String getInstName() {
        return instName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institution.inst_name
     *
     * @param instName the value for institution.inst_name
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setInstName(String instName) {
        this.instName = instName == null ? null : instName.trim();
    }
}