package com.limited.app.bean;

public class Sector {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sector.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sector.sec_name
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private String secName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sector.id
     *
     * @return the value of sector.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sector.id
     *
     * @param id the value for sector.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sector.sec_name
     *
     * @return the value of sector.sec_name
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public String getSecName() {
        return secName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sector.sec_name
     *
     * @param secName the value for sector.sec_name
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setSecName(String secName) {
        this.secName = secName == null ? null : secName.trim();
    }
}