package com.limited.app.bean;

import java.math.BigDecimal;

public class Templatedetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templatedetails.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templatedetails.templateid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templatedetails.alloctypeid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer alloctypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templatedetails.secid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer secid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templatedetails.indid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer indid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templatedetails.interid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private Integer interid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templatedetails.prct
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    private BigDecimal prct;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templatedetails.id
     *
     * @return the value of templatedetails.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templatedetails.id
     *
     * @param id the value for templatedetails.id
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templatedetails.templateid
     *
     * @return the value of templatedetails.templateid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templatedetails.templateid
     *
     * @param templateid the value for templatedetails.templateid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templatedetails.alloctypeid
     *
     * @return the value of templatedetails.alloctypeid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getAlloctypeid() {
        return alloctypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templatedetails.alloctypeid
     *
     * @param alloctypeid the value for templatedetails.alloctypeid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setAlloctypeid(Integer alloctypeid) {
        this.alloctypeid = alloctypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templatedetails.secid
     *
     * @return the value of templatedetails.secid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getSecid() {
        return secid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templatedetails.secid
     *
     * @param secid the value for templatedetails.secid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setSecid(Integer secid) {
        this.secid = secid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templatedetails.indid
     *
     * @return the value of templatedetails.indid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getIndid() {
        return indid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templatedetails.indid
     *
     * @param indid the value for templatedetails.indid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setIndid(Integer indid) {
        this.indid = indid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templatedetails.interid
     *
     * @return the value of templatedetails.interid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public Integer getInterid() {
        return interid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templatedetails.interid
     *
     * @param interid the value for templatedetails.interid
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setInterid(Integer interid) {
        this.interid = interid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templatedetails.prct
     *
     * @return the value of templatedetails.prct
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public BigDecimal getPrct() {
        return prct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templatedetails.prct
     *
     * @param prct the value for templatedetails.prct
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    public void setPrct(BigDecimal prct) {
        this.prct = prct;
    }
}