package com.limited.app.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.limited.app.bean.Alloctype;
import com.limited.app.bean.AlloctypeExample;

public interface AlloctypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alloctype
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int countByExample(AlloctypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alloctype
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByExample(AlloctypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alloctype
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alloctype
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insert(Alloctype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alloctype
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insertSelective(Alloctype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alloctype
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    List<Alloctype> selectByExample(AlloctypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alloctype
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    Alloctype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alloctype
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExampleSelective(@Param("record") Alloctype record, @Param("example") AlloctypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alloctype
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExample(@Param("record") Alloctype record, @Param("example") AlloctypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alloctype
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKeySelective(Alloctype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alloctype
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKey(Alloctype record);
}