package com.limited.app.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.limited.app.bean.AssetinvAlloc;
import com.limited.app.bean.AssetinvAllocExample;

public interface AssetinvAllocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_alloc
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int countByExample(AssetinvAllocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_alloc
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByExample(AssetinvAllocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_alloc
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_alloc
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insert(AssetinvAlloc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_alloc
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insertSelective(AssetinvAlloc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_alloc
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    List<AssetinvAlloc> selectByExample(AssetinvAllocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_alloc
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    AssetinvAlloc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_alloc
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExampleSelective(@Param("record") AssetinvAlloc record, @Param("example") AssetinvAllocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_alloc
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExample(@Param("record") AssetinvAlloc record, @Param("example") AssetinvAllocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_alloc
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKeySelective(AssetinvAlloc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_alloc
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKey(AssetinvAlloc record);
}