package com.limited.app.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.limited.app.bean.AssetinvInter;
import com.limited.app.bean.AssetinvInterExample;

public interface AssetinvInterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int countByExample(AssetinvInterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByExample(AssetinvInterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insert(AssetinvInter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insertSelective(AssetinvInter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    List<AssetinvInter> selectByExample(AssetinvInterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    AssetinvInter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExampleSelective(@Param("record") AssetinvInter record, @Param("example") AssetinvInterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExample(@Param("record") AssetinvInter record, @Param("example") AssetinvInterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKeySelective(AssetinvInter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKey(AssetinvInter record);
}