package com.limited.app.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.limited.app.bean.Assetinv;
import com.limited.app.bean.AssetinvExample;

public interface AssetinvMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assetinv
	 * @mbggenerated  Mon Feb 28 11:07:27 EST 2011
	 */
	int countByExample(AssetinvExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assetinv
	 * @mbggenerated  Mon Feb 28 11:07:27 EST 2011
	 */
	int deleteByExample(AssetinvExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assetinv
	 * @mbggenerated  Mon Feb 28 11:07:27 EST 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assetinv
	 * @mbggenerated  Mon Feb 28 11:07:27 EST 2011
	 */
	int insert(Assetinv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assetinv
	 * @mbggenerated  Mon Feb 28 11:07:27 EST 2011
	 */
	int insertSelective(Assetinv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assetinv
	 * @mbggenerated  Mon Feb 28 11:07:27 EST 2011
	 */
	List<Assetinv> selectByExample(AssetinvExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assetinv
	 * @mbggenerated  Mon Feb 28 11:07:27 EST 2011
	 */
	Assetinv selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assetinv
	 * @mbggenerated  Mon Feb 28 11:07:27 EST 2011
	 */
	int updateByExampleSelective(@Param("record") Assetinv record,
			@Param("example") AssetinvExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assetinv
	 * @mbggenerated  Mon Feb 28 11:07:27 EST 2011
	 */
	int updateByExample(@Param("record") Assetinv record,
			@Param("example") AssetinvExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assetinv
	 * @mbggenerated  Mon Feb 28 11:07:27 EST 2011
	 */
	int updateByPrimaryKeySelective(Assetinv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assetinv
	 * @mbggenerated  Mon Feb 28 11:07:27 EST 2011
	 */
	int updateByPrimaryKey(Assetinv record);
}