package com.limited.app.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.limited.app.bean.AssetinvSecind;
import com.limited.app.bean.AssetinvSecindExample;

public interface AssetinvSecindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_secind
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int countByExample(AssetinvSecindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_secind
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByExample(AssetinvSecindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_secind
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_secind
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insert(AssetinvSecind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_secind
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insertSelective(AssetinvSecind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_secind
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    List<AssetinvSecind> selectByExample(AssetinvSecindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_secind
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    AssetinvSecind selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_secind
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExampleSelective(@Param("record") AssetinvSecind record, @Param("example") AssetinvSecindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_secind
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExample(@Param("record") AssetinvSecind record, @Param("example") AssetinvSecindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_secind
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKeySelective(AssetinvSecind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetinv_secind
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKey(AssetinvSecind record);
}