package com.limited.app.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.limited.app.bean.Industry;
import com.limited.app.bean.IndustryExample;

public interface IndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int countByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insert(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insertSelective(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    List<Industry> selectByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    Industry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExampleSelective(@Param("record") Industry record, @Param("example") IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExample(@Param("record") Industry record, @Param("example") IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKeySelective(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKey(Industry record);
}