package com.limited.app.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.limited.app.bean.Institution;
import com.limited.app.bean.InstitutionExample;

public interface InstitutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int countByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insert(Institution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insertSelective(Institution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    List<Institution> selectByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    Institution selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExampleSelective(@Param("record") Institution record, @Param("example") InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExample(@Param("record") Institution record, @Param("example") InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKeySelective(Institution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKey(Institution record);
}