package com.limited.app.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.limited.app.bean.Inter;
import com.limited.app.bean.InterExample;

public interface InterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int countByExample(InterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByExample(InterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insert(Inter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insertSelective(Inter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    List<Inter> selectByExample(InterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    Inter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExampleSelective(@Param("record") Inter record, @Param("example") InterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExample(@Param("record") Inter record, @Param("example") InterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKeySelective(Inter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inter
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKey(Inter record);
}