package com.limited.app.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.limited.app.bean.Sector;
import com.limited.app.bean.SectorExample;

public interface SectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sector
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int countByExample(SectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sector
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByExample(SectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sector
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sector
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insert(Sector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sector
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int insertSelective(Sector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sector
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    List<Sector> selectByExample(SectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sector
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    Sector selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sector
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExampleSelective(@Param("record") Sector record, @Param("example") SectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sector
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByExample(@Param("record") Sector record, @Param("example") SectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sector
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKeySelective(Sector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sector
     *
     * @mbggenerated Mon Feb 28 11:07:27 EST 2011
     */
    int updateByPrimaryKey(Sector record);
}